name: flutter_robot
description: "Create a widget tests using the Robot Pattern simulating statusBar, opened keyboard, IOS home button, etc"
version: 0.3.3
homepage: https://github.com/RafaelBarbosatec/flutter_robot

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  file: ^7.0.0
  platform: ^3.1.4
  leak_tracker_flutter_testing: any
  meta: any
  test_api: any

dev_dependencies:
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/flutter_robot/fonts/Roboto-Regular.ttf